export type CalculatorId =
  | 'adicional-noturno'
  | 'amortizacao-antecipada'
  | 'auxilio-incapacidade'
  | 'aviso-previo'
  | 'banco-de-horas'
  | 'bolsa-familia'
  | 'bpc'
  | 'cdb-liquido'
  | 'cdb-poupanca'
  | 'cdi'
  | 'conversao-taxa'
  | 'contador-dias'
  | 'custo-demissao'
  | 'custo-funcionario-clt'
  | 'das-mei-atraso'
  | 'das-limite-mei'
  | 'decimo-proporcional'
  | 'decimo-salario'
  | 'dsr'
  | 'emprestimo'
  | 'excesso-limite-mei'
  | 'fator-r'
  | 'ferias'
  | 'ferias-proporcionais'
  | 'fgts-multa'
  | 'financiamento-sac-price'
  | 'horas-extras'
  | 'inss'
  | 'inss-autonomo'
  | 'insalubridade'
  | 'ipva'
  | 'irrf'
  | 'juros-compostos'
  | 'juros-simples'
  | 'lci-lca'
  | 'pensao-alimenticia'
  | 'periculosidade'
  | 'pis'
  | 'plr-ppr-liquido'
  | 'porcentagem'
  | 'pro-labore'
  | 'reajuste-aluguel'
  | 'rescisao-clt'
  | 'salario-liquido'
  | 'salario-maternidade'
  | 'salario-por-hora'
  | 'seguro-desemprego'
  | 'simples-nacional'
  | 'tesouro-selic'
  | 'vale-transporte';

export type CalculatorValues = Readonly<Record<string, number>>;

export type CalculationResult = Readonly<{
  explanation: string;
  label: string;
  value: number;
}>;
